name: Flutter Builds

on:
  push:
    branches:
      - source
  pull_request:
    branches:
      - source

jobs:
  build-windows:
    uses: ./.github/workflows/build-windows.yaml

  build-android:
    uses: ./.github/workflows/build-android.yaml
